# Generated by Django 3.0.5 on 2020-05-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200502_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='cat.jpg', upload_to='profile_pics'),
        ),
    ]
