# Generated by Django 3.0.5 on 2020-05-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20200502_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(default='default.png', upload_to='post_images'),
        ),
    ]
