# Generated by Django 3.0.5 on 2020-05-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20200502_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Image',
            new_name='image',
        ),
    ]
