# Generated by Django 3.0.5 on 2020-05-15 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0028_auto_20200513_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
