# Generated by Django 3.0.5 on 2020-05-19 15:09

from django.db import migrations
import myApp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0029_comment_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=myApp.fields.NonStrippingTextField(blank=True, max_length=250),
        ),
    ]
